# Generated by Django 5.0.4 on 2024-04-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("Happy", "Happy"),
                            ("Normal", "Normal"),
                            ("Sad", "Sad"),
                        ],
                        default="Normal",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
