# Generated by Django 5.1.3 on 2024-11-22 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "choice_text",
                    models.CharField(
                        choices=[
                            ("0", "Extreme"),
                            ("1", "Severe"),
                            ("2", "Moderate"),
                            ("3", "Mild"),
                            ("4", "None"),
                        ],
                        default="4",
                        max_length=1,
                        verbose_name="result",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        help_text="It is a Foreign key with auth.models.User. Used to manage authentication and accounting.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
